### ISSUE TITLE
Asset management for Nova 3

### ISSUE THREAD

**Issue by mooeypoo** [anodyne/nova#235]
I'm getting into fuelphp, and I was going through the Nova 3.0 code. I was wondering if you might want to check into the fuelphp Casset package : https://github.com/canton7/fuelphp-casset 

It seems to have great asset support, including minifying AND including path grouping (which Nova has through the Location controller, instead) It might be a great solution for Nova3.0 and give the ability to provide cache and merging/minifying css and javascript files.

**Comment by agentphoenix** [comment]
Please see #225 

I'm still evaluating whether to use Laravel or FuelPHP, so until that decision is made, any component decisions are on hold.

**Comment by agentphoenix** [comment]
The decision has been made to move forward with Laravel 4, so any asset component that you'd like to see evaluated should A) work with Laravel 4, and B) be installable through Composer on Packagist.

A quick search on Packagist has Assetic as the top asset manager. Take a look and see if this is the sort of thing you're looking for and I'll do some evaluation and see if it makes sense for it to be part of the Nova 3 core.

https://packagist.org/packages/kriswallsmith/assetic

**Comment by mooeypoo** [comment]
Just out of curiosity, can you say why you're switching? Seems like Nova3's core was moving along well in FuelPHP. And the issue of "bundles" is covered in Fuel with packages and modules, so I thought the two platforms were more of a style choice... they're fairly alike, especially in terms of modularity.

I'm just curious if you found something that makes Laravel better than Fuel in the sense of rewriting the core you already have for Nova3?

(I'd love to help out core stuff if you need me, I am already familiar with Fuel but I can go through Laravel, I'm just curious to know why you made the decision?)

**Comment by agentphoenix** [comment]
This is the kind of thing I've been wrapped up in for months, so it's tough to highlight _all_ the reasons, but I can certainly give you some examples of why Laravel over Fuel.

Laravel has always been a framework that's intrigued me, but version 3 didn't really suit Nova that well. We could've made it work, but it would've been a stretch. When version 4 started being built, I kept my ear to ground about what was happening with that. After spending a bunch of time working in Laravel 4, it strikes me as the better of the two options, not just for now, but for beyond Nova 3 as well.

You are correct that Fuel has built-in modules (I've had to make some changes to allow for the same functionality in L4), but L4 is built off the idea of using framework-agnostic components from around the PHP world and tying them together. One of the big movements in the PHP community over the last year is building framework-agnostic components and distributing through Packagist (to be installed via Composer). It's actually a really slick way to handle dependencies. When I'm developing I can run a command and get the latest updates to L4 and all its components and then lock things down when it's time to release. (I'm still working through that kind of stuff, but that's the general idea.)

L4 is right there at the forefront with this kind of stuff and using these framework-agnostic components. For example, the entire Request/Response component is derived from Symfony's HTTP Foundation and HTTP Kernel components. No reinventing the wheel, just using what's already out there. That's the philosophy behind L4: using decoupled components. The awesome part is that if a core Laravel component isn't right for Nova, I can easily find one that is on Packagist (or write one myself) and swap it out without much effort. As an example, by default, L4 only loads config files from one location, but Nova needs to store config items in the core and then be able to override them from the `app`. I was able to write a config loader that does this and just swaps out Laravel's config loader for my own through the DI container. This kind of flexibility is **huge** and not something easily afforded by Fuel, if at all in some cases. (What's cool is that I'm pulling in a Fuel component to help with some of the filesystem stuff that I need to do in Nova 3, so I'm using stuff from _all_ over the place.)

It's true that Fuel is marching toward their 2.0 version, but from everything I've read so far (and it's changing a lot), it's more complicated than I care to see. Honestly, it feels like Fuel 2.0 is just going to be their own version of Laravel without much distinction, just a different way of doing things. That's fine, but if given the choice between the two, Laravel just seems like a more elegant solution. It just seems like Fuel has lost their way (as well as several people leaving the core development team, one of which has switched most of his projects over to L4) and are floundering a bit. That's concerning to me, especially when I think beyond Nova 3 at what things might look like down the road.

I've put a lot of thought into this because I'm not interested in building Nova 3 and then switching frameworks again down the road. The hope here is to do this one more time and be done with it. L4's flexibility provides ample opportunity to expand in the future because of all the decoupled components and being able to swap things out if need be. With things like CodeIgniter, Kohana and Fuel 1.x, that's not really a possibility; you get locked in to a certain way of doing things and a smaller subset of components. Laravel offers greater flexibility, easier testability and some pretty slick features (their ORM is killer, they have a dead simple email wrapper, a very cool queue system and the way they handle routing is second-to-none).

The best part is that a lot of what's already been written for Nova 3 in Fuel (which wasn't much) can be ported over to L4 without a ton of extra effort. For example, in the matter of a couple of days, I've ported a big chunk of the setup package over to Laravel and even managed to improve what was written before.

The best thing to do is start reading up on L4 (http://four.laravel.com) and let me know if you have any questions about Laravel or Nova 3. If it's easier to jump on IM some night, I'm happy to do that too. Hopefully this helps clarify things.

**Comment by mooeypoo** [comment]
Thanks! I wasn't aware of the complete agnosticism of Laravel4, I was under the impression the two platforms are relatively similar with small distinctions (like the way they choose to utilize ORM, etc) and differences in flow - but this is a great point. 

I'll definitely read up on Laravel4 and start playing around with it, that's probably the best way to actually experience the differences. Will the new Nova version (based on Laravel) be up on GitHub in the Nova3 repo? I'd love to go over that and get myself into the core so I can help, in case you need me to.

**Comment by agentphoenix** [comment]
L4 isn't _completely_ agnostic. They do have their own components, but like I said, most of those could be swapped out if necessary (though in reality, you'd probably be more likely to pull their pieces into your own projects, not vice versa). L3 and Fuel 1 are very similar, but L4 is a pretty big departure from L3.

There's actually a new repo at `anodyne/nova3` that has the current version of what I've been working on. It's very broken at the moment. Installation doesn't work, so the best way to play around with it is to install the Fuel version of Nova 3 into a database then point the L4-Nova files to that database.

I can give you a hand with that stuff over IM if you need this weekend. Just let me know. There may a lot of things that need explaining at this point.
