### ISSUE TITLE
Who's Online Isn't Working

### ISSUE THREAD

**Issue by diziara** [anodyne/nova#308]
It hasn't worked since the upgrade to 2.7 for PHP8 and the newer version of Code Igniter. I did add `$config['sess_driver'] = 'database';` to my config file. I've verified that it doesn't work under the default skins, and I do not have the admin index page overridden. I'm unsure where else to check at this point to get it working.

**Comment by agentphoenix** [comment]
CodeIgniter 3 changed the way timestamps are stored for sessions in the database and it's become a rat's nest of settings that need to line up. Ultimately it depends 100% on time zone settings lining up with what the server has configured. I've spent hours trying to sort it all out and don't have a bulletproof solution.

You can try messing around with the time zone settings for the site and your account, but even if you get it working for yourself, it'll likely break for someone else.

Sorry I don't have a better answer, but the feature is a total abuse of the database sessions feature, so I'm not really interested in pouring more time in to it than I already have at this point.

**Comment by diziara** [comment]
Okay.

1. Could you add a note into the Nova docs mentioning that this is a known issue, so that people coming behind me know it's not just them messing something up but that it's finicky.

2. Can you recommend any resources for me to poke through if I want to attempt to figure this out?

Thanks!

**Comment by agentphoenix** [comment]
I'm happy to add something to the documentation. Do you have a recommendation about where in the documentation you would go looking for that information?

**Comment by agentphoenix** [comment]
One thing you can try is to override the model that pulls that information out of the database. I believe we tried this when debugging the issue and it didn't resolve the problem, but it's worth a try if it's a feature that's important to you.

You can add the following code to the `application/models/User_model.php` file:

```php
public function get_online_users($time = 5)
{
    $final_time = time() - ($time * 60);

    $this->db->from('sessions');
    $this->db->where('timestamp >=', $final_time);

    $query = $this->db->get();

    $array = [];

    if ($query->num_rows() > 0) {
        foreach ($query->result() as $row) {
            if (! is_null($row->data) and ! empty($row->data)) {
                $item = Util::unserializeSessionData($row->data);

                $array[] = (isset($item['userid'])) ? $item['userid'] : false;
            }
        }
    }

    return $array;
}
```

The code in the core uses CI's `now()` helper which can return different values based on a variety of factors (something that wasn't clear at the time it was built). Some of the factors that go into what it returns are actually at the server level which makes it more challenging to address safely and in a way that doesn't potentially throw off all timestamps in the application.

The above code attempts to do the session query by using UTC time and parsing backwards rather than potentially getting _local_ time and parsing backwards (which potentially creates an unwanted to shift and starts to show incorrect data). It might resolve your issue, but some people that made a similar change actually saw things get worse as a result. You'd want to make sure you were testing with users in different time zones as yourself to verify it's doing what you want / expect.

**Comment by diziara** [comment]
I'll poke at that later today. When I was making a blind attempt to figure out what wasn't working, I see that the database saves the timestamp as unix epoch. I think Dreamhost has my VPS set to Pacific time, but I'll verify that when I start poking at things.

As for where to put the info in the docs, it might be a good idea to give it its own section, maybe under the resources section, and link to it from a note in the upgrade section where you mention the setting to add to `config.php`. While most people probably have done that upgrade to 2.7 by now, it's probably the first place they'd look if they decided to go back and attempt to get it working.

**Comment by agentphoenix** [comment]
If your server is set to Pacific time, then the query it's running is starting from a much different time than UTC, so the code I provided may resolve the issue for you.

**Comment by diziara** [comment]
Okay, in theory it looks like the code you provided is working on my test site. I tried it with two users set to different timezones, but I'm waiting for someone else to be able to log in with their account to verify it works for them before I drop it on my active site.

You said that for some people it made things worse. Can you tell me what they were seeing when it did, so I know to watch out for it?

**Comment by agentphoenix** [comment]
People would see it say no one was online even when they were online or people would show as online hours after the fact.

**Comment by agentphoenix** [comment]
@diziara Planning to make this change in 2.7.11 unless you've seen issues with it so far.
