### ISSUE TITLE
Installing/un-installing MODs

### ISSUE THREAD

**Issue by ghost** [anodyne/nova#36]
Need a mechanism for installing and uninstalling MODs

**Comment by mooeypoo** [comment]
If you need help with the strategy on this, I have some thoughts on the matter. It could be a relatively simple procedure with an XML file detailing the structure of the MOD and its version (which would also serve as a version comparison), a conformed way to state which table and fields should exist. This could then serve as the infrastructure to tell an installer where to copy the files (inside /third-party, probably) and what to add to the sql tables -- the custom sql tables that the mod needs but also menus and parameters directly to the nova_ basic tables.

Uninstall would just follow the same idea only backwards, since there's an XML file to dictate the way.

**Comment by agentphoenix** [comment]
We're actually going to go with a much simpler way to do this through migrations in Nova 3. Developers will be able to write their own _up_ and _down_ methods to describe how to install and uninstall a mod. More information will be coming as the whole thing takes shape.
