### ISSUE TITLE
Rendering Text from Right -> Left for Hebrew

### ISSUE THREAD

**Issue by AlPrunty** [anodyne/nova#88]
For possible Hebrew language file text needs to be rendered in Right to Left fashion instead of Left to Right.  Not a priority, but there are languages that go "backwards"

**Comment by anodyne** [comment]
Need to make changes to all the template files if this is going to be done. May or may not make it for 1.0, might get pushed to 1.0.1 or 1.0.2 depending on a few things.

http://drupal.org/node/433906

**Comment by AlPrunty** [comment]
Take your time... I don't know anyone who needs it yet... just thought it would be a good thing to add at a later date.  It's not a BUG though... guess it's a feature.

**Comment by anodyne** [comment]
This actually should be dealt with before 1.0 since it involves template changes. Better to get those in at the start then try to get everyone to update their skins. I'll have to push some changes to the repo tonight at which point you'll need to pull the changes and do a quick and dirty translation into a language that requires RTL text rendering so you can let me know the kinds of things that'll need to be updated.

**Comment by AlPrunty** [comment]
Just let me know the language file and I'll play with it.

**Comment by anodyne** [comment]
I'm actually going to pull all of this out of the repository. There's more involved with this than I want to deal with this close to release. It'll have to wait until the next major release of Nova.

**Comment by AlPrunty** [comment]
That may actually be a wise thing to do... I do have friends that Sim in Israel, they have done without SMS so far <G>.

Actually until I know how to skin and edit languages I doubt I would be able to do anything to make it work at this point.  As they say... Basics first
